Task06-fp-yat, Group 04, Курносова Полина
yeputons/hse-2019-pb-tasks pull request #491
Opened 2020-04-04 13:16 UTC by shesea

Мне так жаль.........................

2020-04-04 20:23 UTC, olgalupuleac requested changes
* showProgram
	* Корректность есть
* eval
	* Корректность есть

2020-04-04 20:23 UTC, olgalupuleac commented on task06-fp-yat/Yat.hs
> +getCond :: (State, Integer) -> Expression -> Expression -> [FunctionDefinition] ->(State, Integer)
Мне кажется, это лучше не выделять в отдельную функцию, а просто разобрать при помощи guard'ов внутри `Conditional`

2020-04-04 20:23 UTC, olgalupuleac commented on task06-fp-yat/Yat.hs
> +getEvaled state func e =
Мне кажется, что лучше использовать `where`, а не `let`. В остальных местах аналогично

2020-04-04 20:23 UTC, olgalupuleac commented on task06-fp-yat/Yat.hs
> +evalExpression state func (Block  args)            = foldl (\(s, val) arg -> evalExpression s func arg) (state, 0) args
Не хватает перевода строки в конце

2020-04-14 16:37 UTC, yeputons commented
Дедлайны прошли.

2020-04-14 16:37 UTC, closed without merging